version: 2.1

orbs:
  node: circleci/node@4.7.0

jobs:
  build:
    docker:
      # specify the version you desire here
      - image: cimg/node:17.2.0

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: ./node_modules/.bin/greenkeeper-lockfile-update
      - run: npm run build

      # run tests!
      - run: npm run test

      # send code coverage info to coveralls
      - run: cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

      - run: ./node_modules/.bin/greenkeeper-lockfile-upload
